### ISSUE TITLE
Error when training with loc_type=1

### ISSUE THREAD

**Issue by jiahaowork** [GriffinLiang/vrd-dsr#21]
I tried to run ~/tools/train.py with params --dataset vrd --loc_type 1 but got the following error.

Namespace(ds_name='vrd', epochs=5, loc_type=1, lr=1e-05, model_type=None, name=None, print_freq=10, resume='', start_epoch=0, use_obj=True, use_obj_prior=True, use_so=True)
Traceback (most recent call last):
  File "train.py", line 119, in <module>
    train_net(train_data_layer, net, epoch, args)
  File "/home/ljh/vrd_dsr/vrd-dsr/tools/../lib/model.py", line 28, in train_net
    obj_score, rel_score = net(image_blob, boxes, rel_boxes, SpatialFea, classes, ix1, ix2, args)
  File "/home/ljh/anaconda2/envs/caffe2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ljh/vrd_dsr/vrd-dsr/tools/../lib/nets/Vrd_Model.py", line 119, in forward
    lo = self.fc_lov(SpatialFea)
  File "/home/ljh/anaconda2/envs/caffe2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ljh/vrd_dsr/vrd-dsr/tools/../lib/network.py", line 30, in forward
    x = self.fc(x)
  File "/home/ljh/anaconda2/envs/caffe2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ljh/anaconda2/envs/caffe2/lib/python2.7/site-packages/torch/nn/modules/linear.py", line 55, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/ljh/anaconda2/envs/caffe2/lib/python2.7/site-packages/torch/nn/functional.py", line 1026, in linear
    output = input.matmul(weight.t())
RuntimeError: size mismatch, m1: [320 x 32], m2: [8 x 256] at /pytorch/aten/src/THC/generic/THCTensorMathBlas.cu:249

Any solutions? Thank you!

**Comment by lileilai** [comment]
@jiahaowork have you solve the problem of  "loc_type=1" ? thanks

**Comment by jiahaowork** [comment]
@lileilai No, it won't work.
